services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Lukasbableck\ContaoFolderDownloadBundle\:
        resource: ../src
        exclude: ../src/{Resources}
    Lukasbableck\ContaoFolderDownloadBundle\EventListener\:
        resource: ../src/EventListener
        public: true